display:
  default:
    display_title: 'Por defecto'
    display_options:
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ anterior'
            next: 'siguiente ›'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        comment_bulk_form:
          action_title: Acción
        operations:
          label: Operaciones
      filters:
        langcode:
          expose:
            label: Idioma
  page_unapproved:
    display_options:
      filters:
        langcode:
          expose:
            label: Idioma
      fields:
        comment_bulk_form:
          action_title: Acción
        operations:
          label: Operaciones
