label: Multimedia
display:
  default:
    display_title: 'Por defecto'
    display_options:
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        media_bulk_form:
          action_title: Acción
        bundle:
          label: Tipo
        status:
          label: Estado
          settings:
            format_custom_true: Publicado
            format_custom_false: 'Sin publicar'
        operations:
          label: Operaciones
      filters:
        bundle:
          expose:
            label: Tipo
        status:
          group_info:
            group_items:
              1:
                title: Publicado
              2:
                title: 'Sin publicar'
        langcode:
          expose:
            label: Idioma
      title: Multimedia
  media_page_list:
    display_title: Multimedia
    display_options:
      menu:
        title: Multimedia
