label: Contenido
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        title:
          label: Título
        status:
          label: Estado
          settings:
            format_custom_true: Publicado
            format_custom_false: 'Sin publicar'
        operations:
          label: Operaciones
      filters:
        title:
          expose:
            label: Título
        status:
          expose:
            label: Estado
          group_info:
            group_items:
              1:
                title: Publicado
              2:
                title: 'Sin publicar'
        langcode:
          expose:
            label: Idioma
      title: Contenido
    display_title: 'Por defecto'
  page_1:
    display_options:
      menu:
        title: Contenido
      tab_options:
        title: Contenido
    display_title: Página
